name: PR
on: [pull_request]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'check-types']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version: "20"

    - name: Install dependencies
      run: |
        pnpm install --immutable

    - name: ${{ matrix.step }}
      run: |
        pnpm ${{ matrix.step }}
